Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: STD21102
  MyBucketNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/mybucket/name"
      Description: "Name of my S3 bucket"
      Type: "String"
      Value: !Ref MyBucket
  MyBucketArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/mybucket/arn"
      Description: "ARN of my S3 bucket"
      Type: "String"
      Value: !GetAtt MyBucket.Arn
